env:
  global:
    - CIBW_TEST_REQUIRES=nose
    - CIBW_TEST_COMMAND="nosetests {project}/test"
    - TWINE_USERNAME=aflc
matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      env:
        - INSTALL_SOURCE=true
    - os: osx
      sudo: required
      language: generic

script:
- |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      virtualenv .env
      source .env/bin/activate
      which python
      which pip
    fi
- pip install cibuildwheel==0.10.1 twine
- cibuildwheel --output-dir wheelhouse
- |
    if [[ $TRAVIS_TAG ]]; then
      if [[ -n $INSTALL_SOURCE ]]; then
        python setup.py sdist
      fi
      twine upload wheelhouse/*.whl
    fi
