services: docker
sudo: required
os: [osx, linux]
      

script:
  - pip install cibuildwheel==0.6.0
  - pip install cython
  - cibuildwheel --output-dir wheelhousea
  - pip install -e wheelhouse
  - python editdistance/test_editdistance.py
