language: python
python: ['2.7', '3.6']
matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

script:
  - pip install cibuildwheel==0.6.0
  - pip install cython
  - cibuildwheel --output-dir wheelhousea
  - pip install -e wheelhouse
  - python editdistance/test_editdistance.py
